### ISSUE TITLE
Publish the renovate image as a verified image in Docker Hub

### ISSUE THREAD

**Issue by gomesp** [renovatebot/docker-renovate#242] opened 2021-12-21 21:05 UTC
Hi team

Thanks for this great product. Would it be possible to publish the docker image as [Verified Publisher Image](https://docs.docker.com/docker-hub/publish/) or [Official Image](https://docs.docker.com/docker-hub/official_images/)? 

A few companies I work with do not allow Docker images that are not verified or official to be used. :(

**Comment by viceice** [comment] 2021-12-21 21:26
Duplicate of #19

**Comment by rarkins** [comment] 2021-12-21 21:27
@viceice I think this is different to signing?

I don't think that Renovate qualifies for official images, while "verified publisher image" looks like a revenue generating exercise from Docker aimed at commercial companies. So unfortunately neither looks feasible.

**Comment by viceice** [comment] 2021-12-21 21:28
Yes, sorry. Misinterpreted.

**Closed** 2024-02-09 15:02 UTC
